spring:
  application:
    name: lab-management

  datasource:
    url: jdbc:mysql://localhost:3306/lab_management?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  sql:
    init:
      mode: never
#      data-locations: classpath:data.sql
#      continue-on-error: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB

# JWT Configuration
jwt:
  secret: your-256-bit-secret-key-change-this-in-production-environment
  expiration: 86400000 # 24 hours in milliseconds

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging
logging:
  level:
    com.lab.management: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# File Upload
file:
  upload-dir: uploads
